package com.ukyu.base.exception;

/**
 * 异常的处理
 * # 异常是一个事件，当异常发生时，会破坏正常的程序流程
 */
public class ExceptionDemo {
    public static void main(String[] args) {
        try{
            int i = 0;
        }
        catch (Exception ex1)
        {
        }

        // Chained Exceptions


    }
}
